window.COFORYOU_SEEDED_MINUTES = [
  {
    "id": "anniversary-review-2026-08-w2-claudia",
    "department": "Team",
    "title": "周年庆复盘",
    "meetingDate": "2026-08-W2",
    "participantName": "Claudia",
    "minutes": "直播执行与协作\n- Fyfy 准备直播所需样品与道具，Wenqi 和 Ebel 再 double check。\n- 以后产品若需要教程，可提前熟悉使用方式并与 Coco align。\n- 抽奖 comment pin 好后马上给 Coco signal。流程：signal → 抽奖 → cue 公布 → pin。下单和开放抽奖都等 Jimun cue，她确认后再进行。\n- 直播画面：需要长期才能看到效果的产品，如面膜、光学、device 等，要准备对比图。\n- Tefal 要提前开始铺垫煮饭内容。\n- 直播前 meeting 定下当天值日生。\n\n合规与宣传用词\n- 保健品要先 align，不要说每个人都需要；应教育观众按自身身体状况判断是否需要 supplement。\n- 口服产品可注明：效果因人而异，可以根据自己身体需求选择。孕妇、小孩及坐月子的妈咪尤其要提醒。\n- Begin 不需要强调减脂。Roasted chicken 的鸡皮较油，应教育观众去皮后食用，而且 protein 也不足。以后用词不要夸大，可适当表达。\n- 拼单要活跃群组，并教育大家如何使用和拼单。\n\n品牌复盘\nRosewhite\n- 可以一起打卡，融入自己的生活状态，展示 after 状态。每个女生都不同，不只是痘印变淡或变白。\n\nd'Alba\n- 已经卖过很多次，可更 focus 在介绍配套。\n\n可复美\n- 说明为什么买两个的配套，以及划算在哪里。\n- 同一内容重复讲时，可比较图文或 video 讲解哪种更吸引观众；有讲解时销量有时会上升很多。\n\nJmoon\n- 品牌本身 branding 不够，只能用较浮夸的带货方式表现，但这不是我们的直播方式，因此观众下单冲劲不足。\n\nBegin\n- 口味变少。\n- 可以多拍大家一起吃的 scene。\n\nSatu\n- 干发喷雾推了一下后 sales 上升很多，可持续观察。\n- 前期可以拍大家在公司使用的 video。\n\nAlbert Wines\n- 下次可调整配套组合，节点也是问题。\n- 团队对酒不熟悉，可用更接地气的方式记录：小编不太会喝，但品尝后对某一款印象深刻，不一定要很专业地介绍。\n- 品牌提供的 PPT 与实际资料有出入，双方需要 double check。\n\nProya\n- 下次再尝试符合自己 style 的推广方式。\n\nGutshake\n- 下次可直接主推大配套。\n\n小红书\n- 可以再多推动 XHS 晒单。\n\nSantan\n- 食品类不健康或重要的 ingredients label 可直接加入 FAQ，引导观众查看。\n\nShu Uemura\n- 要教育观众如何乳化及正确使用，并展示效果。\n\n延长开卖\n- 延长开卖主要提醒观众产品仍在售，不需要重新 hard educate。",
    "summary": "会议重点\n- 直播前完成样品、道具、产品用法、抽奖节点及值日生安排；Fyfy 负责准备，Wenqi 与 Ebel 复核，Jimun 负责抽奖 comment/pin 并即时给 Coco signal。\n- 功效型产品需准备清楚的视觉对比；直播团队应提前熟悉教程，不在直播中临时摸索。\n- 保健品、口服产品和食品宣传必须避免绝对化及减脂承诺，注明效果因人而异，并提醒孕妇、小孩及产后人群咨询专业人士。\n- 拼单群需主动经营并教育用户操作；延长开卖以提醒仍可购买为主，不重复进行高强度教育。\n\n品牌方向\n- d'Alba、可复美：减少重复功效介绍，突出配套价值、双盒优惠及图文/视频转化表现。\n- Rosewhite：以生活化打卡与个人状态变化建立陪伴感。\n- Jmoon、Proya：重新寻找符合 Coforyou 风格的推广表达，避免单纯复制品牌的浮夸带货方式。\n- Begin、Satu：增加团队真实使用/食用场景；Begin 同时修正减脂与营养表达。\n- Albert Wines：调整配套和销售节点，以接地气的品酒体验呈现，并与品牌双向核对资料。\n- Gutshake 主推大配套；Santan FAQ 加入 ingredients；Shu Uemura 强化乳化教学；持续推动 XHS 晒单。\n\nAction Items\n- Fyfy 准备直播样品/道具，Wenqi 与 Ebel 完成复核。\n- Jimun 建立统一抽奖 signal、post、pin、cue 流程。\n- Content 为长期功效产品准备对比素材，并制作 Satu/Begin 团队场景内容。\n- 所有口服、保健品和食品内容统一加入合规免责声明及特殊人群提醒。\n- Brand/Content 在直播前核对 Albert Wines 等品牌资料、配套及推广节点。",
    "createdAt": "2026-08-11T08:10:00.000Z",
    "locked": true
  },
  {
    "id": "anniversary-review-2026-08-w2-fyfy",
    "department": "Team",
    "title": "周年庆复盘",
    "meetingDate": "2026-08-W2",
    "participantName": "Fyfy",
    "minutes": "1. 全场复盘\n- 样品准备：不确定是否需要展示的产品，可提前询问 Ebel 与 Wenqi。\n- MIC 问题：Jimun 加上 Pop Up，提醒观众可退出直播间后重新进入。\n- 产品熟悉度：即使不是主推产品，拍摄期间也应先 align 所有使用方式。\n- 抽奖流程：设定抽奖时间。主播一讲抽奖，后台 Jimun 发出内容并 pin，完成后直接通知主播。\n- Pop Up：Angeline 准备 pop up 时需抓准重点；Jimun 做 pop up 时同步执行。功效类产品可放对比图，其余可参考平时 content，把 video 放进去。\n- 评论区：IG DM 较少时，Alyssa 可直接在直播 comment 区回复“已私信顾客，可注意查看”。\n- 流量转化：未开卖 Reels 设置 reminder，已开卖 Reels 直接加 product link；教育观众从对应品牌 Reels 点 product 下单。Fyfy 向 Shopee 确认 IG Reels 挂链接的其他方案。\n- 值日生：直播前 meeting 定下当天值日生，Fyfy 记录，团队轮流。\n- Supplement：不教育每个人都需要，不说“一定需要/一定有效”；所有保健品 content 加免责声明，BD 一开始说明孕妇、月子、小孩的禁忌。\n- 食品 Content：例如 Begin 要更仔细了解 ingredient/成分，注意用词，不夸大或承诺功效。\n- 可拼单品牌：开卖前 meeting 提醒，活跃拼单群，让大家养成使用习惯。\n\n2. 各部门\nContent\n- Campaign 前为每个品牌开 meeting 对齐 direction。\n- 特价表若少资讯，不要直接删除，可重新发布；Angeline 在群内发最新海报 file + link，Fyfy double check 特价表确认后才发布。\n- 样品分配：Content 与 Coco 讨论后，Fyfy 向品牌拿样品。\n- Extend 团购：提前说明会延长；所有品牌开卖后才继续铺，期间聚焦未开卖品牌。Extend 只是增加品牌和顾客下单时间。\n- 下单链接发布前 double check，避免链接或价格错误。\n\nCS\n- 售后问题：d'Alba 首 100 位、Santan 少货。处理方式为“问题 + solution”发大群，Notice 和 Telegram 发公告，Coforyou 发 video。\n- Telegram 群组难以同时 focus；拼单群禁止其他人转卖，可设 rules，违规者移出。\n- 小福管家可以制作表情包。\n\n3. 品牌复盘\nd'Alba\n- 带过多次且新品话题不强，可更注重配套价格和福利。\n\nRosewhite\n- 下次提前提醒拼单；教育产品知识并以平台方式带观众打卡、改善状态与精气神。\n\n可复美\n- 记录待补充。\n\nJmoon\n- Branding 不足，品牌需要较浮夸铺垫但团队没有做到；下次调整推广方式。\n\nBegin\n- 口味选择减少可反馈品牌；多拍大家一起吃，让观众感到团队认可且好吃。\n\nSatu\n- 展示不同人的氛围感、不同发型，让精致产品在不同人身上都呈现美感。\n\nAlbert Wines\n- 配套设计更灵活，让顾客自行选择，减少大配套；选择圣诞、新年等合适节点。\n- 试酒拍摄若当下不熟悉，可后续再尝试并记录味道。品牌资料有误，除品牌 double check 外，团队也需复核。\n\nProya\n- 像 d'Alba 一样拍清楚每个配套能得到什么，并建立 Coforyou 自己的推广 style。\n\nGutshake\n- 延续大配套，品牌需提供更多不同福利。\n\nSantan\n- 后续 feedback 发货；所有食品类 ingredient list 放入 FAQ。\n\nShu Uemura\n- 参考 XHS，展示卸妆能力，放大乳化和溶解妆容的效果。",
    "summary": "会议重点\n- 直播前需完成样品确认、全产品使用方式、值日生、抽奖时间和 Pop Up 素材的统一检查。\n- Jimun 负责后台抽奖发布与 pin 后即时通知主播；Angeline 把握 Pop Up 重点；Alyssa 在 DM 较少时主动处理直播评论；Fyfy 记录值日生并跟进 Shopee Reels 挂链接方案。\n- Reels 在未开卖时加 reminder，开卖后加 product link；所有链接和价格发布前必须 double check。\n- 保健品、口服和食品内容不作绝对承诺，加入免责声明、特殊人群禁忌及 ingredient 信息。\n- 拼单群要在开卖前预热并设立禁止转卖规则；售后问题统一以“问题 + solution”同步大群、Notice、Telegram 和 Coforyou 内容。\n\n部门行动\n- Content：每个 campaign 前对齐品牌方向；特价表更新需标记最新版，不删除旧讯息后不说明；与 Coco 确认样品后由 Fyfy 向品牌索取。\n- CS：整理 d'Alba/Santan 售后公告流程，制定 Telegram 拼单群规则，并发展小福管家表情包。\n\n品牌方向\n- d'Alba/Proya/可复美：强化配套所得、价格福利和 Coforyou 自有表达。\n- Rosewhite：结合拼单、知识教育与生活打卡。\n- Jmoon：调整前期铺垫和推广方式。\n- Begin/Satu：增加多人真实场景与不同人物呈现。\n- Albert Wines：优化自由搭配、销售节点、试酒记录和资料复核。\n- Gutshake 延续大配套并争取更多福利；Santan FAQ 加 ingredient list；Shu Uemura 放大卸妆乳化过程。",
    "createdAt": "2026-08-11T08:11:00.000Z",
    "locked": true
  },
  {
    "id": "anniversary-review-2026-08-w2-ebel-wenqi",
    "department": "Team",
    "title": "周年庆复盘",
    "meetingDate": "2026-08-W2",
    "participantName": "Ebel & Wenqi",
    "minutes": "1. Brand Review\n整体建议\n- 周年庆前先 brief 每个 Brand 的推广方向，并提前与 Coco 及团队 align，让 Content 前期已有明确方向，不在直播前才调整。\n\na. d'Alba & Proya\n- 已带过多次，消费者熟悉度高。d'Alba 新品话题性较弱，教育内容空间有限。\n- 后续重点转向配套价值、优惠机制及不同族群搭配，不重复介绍功能。\n- 补充：让观众看到买到什么、得到什么，并找到 Coforyou 自己的推广 style。\n\nb. Rosewhite\n- 提前规划拼单机制，提高客单价和互动率。\n- 除了 fundamental 教育，也呈现状态变化，与观众同步打卡，制造期待和陪伴感。\n\nc. 可复美\n- 让大家直观看到两盒装次抛到手有多划算。\n\nd. Jmoon\n- 样品分配和沟通需更明确，避免理解落差影响 Content 拍摄。\n- 没有给观众看到很直观的对比。\n\ne. Albert Wines\n- 商品受季节性影响明显，需评估更合适节点。\n- 若遇到需要记忆风味但当下无法形容，要与 Coco align。\n- 品牌 PPT 与直播资料有出入。\n- 不会品酒也可以接地气介绍，例如哪一瓶印象最深，用更 fun 的方式。\n\nf. Satu\n- 前期多呈现不同人的氛围感，例如每个人化妆、绑不同发型。\n\ng. Begin\n- 口味选择较少，可能影响购买意愿。\n- 增加多人一起吃的场景。\n\nh. Santan\n- 加强多人分享和家庭聚餐方向。\n- 所有食品类 FAQ 一定放 ingredient，引导观众查看 FAQ。\n\ni. Shu Uemura\n- 配套吸引力不足，新品卖点不明确，教育内容偏少。\n- 增加产品教育，参考 XHS，用心拍卸妆过程并放大乳化、溶解妆容画面，妆要够浓。\n\nj. Gutshake\n- 暂无。\n\n2. 整体流程优化\n特价海报发布时间\n- 发布时间较晚，影响 Content 安排；Story 发布后仍需删除重发，增加重复工作并影响用户观感。\n- 建议确认最终版本后才交由 Content 发布。\n\nFAQ／海报\n- 出错时直接删除且未说明更新内容，容易造成混淆。\n- 修改时说明调整内容，并标注 Latest Version／Updated Version。\n\n样品分配\n- 部分 Brand 样品分配不明确，例如 Albert Wines 的 Coco 主推样品不足、Jmoon 因沟通理解落差出现分配问题。\n- Coco 主推可优先获得完整样品；建立样品分配清单，并在 meeting 一起 align。\n\n3. 周年庆延长开卖安排\n- 需评估延长是否符合活动节奏。连续直播下，Content Team 要同时兼顾上一场宣传与下一场预热，资源容易分散并影响后续品牌内容品质。\n- 建议在会议中提前 align 延长期间的铺垫方向。\n\n4. 直播\n- Content Team 提前整理 Run Down、抽奖时间及重要节点并同步团队。\n- 直播前完成商品、赠品、展示样品检查；不确定是否展示可提前询问主播。\n- 很重要的信息直接传达给小编，不只发在群里，以免遗漏。\n- 小编提前熟悉每款产品使用方式、卖点和展示流程。\n- 加码抽奖可在 CS Group 通知；最终由 Jimun 直接喊。\n- 直播后 Reels 可提前加 reminder，开卖后 edit Reels 挂链接。\n- Supplement/口服/食物宣传注意用词，不保证功效；Story 标注“效果因人而异，可先咨询医生”，并特别提醒孕妇、小孩、坐月子人群。Begin 不能以减脂为方向，三餐只吃 Begin 也不健康。\n- Story 宣传期间引导拼单。",
    "summary": "核心结论\n- 周年庆及后续 campaign 必须在前期完成每个品牌的推广方向 brief，并与 Coco、Content 和相关团队统一，避免直播前临时调整。\n- 直播 Run Down、抽奖节点、样品清单、赠品和展示流程应在直播前完成；关键讯息需直接通知执行人，不能只留在群组。\n- 特价海报和 FAQ 必须确认最终版后发布；修正时说明改动并标记 Latest/Updated Version。\n- 样品分配建立清单，Coco 主推品牌优先安排完整样品。\n- 延长开卖会分散 Content 对下一场品牌的资源，必须先确认目的并提前制定铺垫方向。\n\n品牌策略\n- d'Alba、Proya、可复美：从重复功效教育转向配套价值、优惠与“买到/得到什么”的直观展示。\n- Rosewhite：提前设计拼单，以打卡和状态陪伴增强互动。\n- Jmoon：修正样品沟通并增加直观对比。\n- Albert Wines：选择合适季节，以不专业但真实有趣的品酒体验表达，并复核品牌资料。\n- Satu、Begin、Santan：增加多人、生活及家庭场景；食品 FAQ 加入 ingredient。\n- Shu Uemura：加强新品教育，以浓妆卸除、乳化及溶解过程作清楚视觉展示。\n\n合规要求\n- 保健品、口服品及食品不得承诺功效；统一加入效果因人而异和咨询医生提示，并明确孕妇、小孩、坐月子人群注意事项。Begin 不以减脂为宣传方向。",
    "createdAt": "2026-08-11T08:12:00.000Z",
    "locked": true
  },
  {
    "id": "anniversary-review-2026-08-w2-angeline",
    "department": "Team",
    "title": "周年庆复盘",
    "meetingDate": "2026-08-W2",
    "participantName": "Angeline",
    "minutes": "样品与道具展示不全\n- 开播后发现样品和道具不足，无法完整展示所有配套。\n- 直播前必须由团队一起清点并走一遍配套清单，确保每个配套对应产品和道具齐备且按顺序摆放。\n\n麦克风收音异常\n- 暂时排除硬件后，推测为 Instagram 系统 Bug。\n- 主播及后台用 Pop-out 图卡或置顶评论提醒观众：如遇无声音，请退出直播间后重新进入。团队继续测试设备和网络通道。\n\n主播与 Content Team 产品熟悉度\n- 讲解不够深入或解答不够精准。\n- 重点拉通产品核心卖点、使用方法及搭配逻辑；对成分、功效、适用人群和常见问答做到完整熟悉。\n\n抽奖流程与时间不同步\n- 前台主播、后台客服与观众端节奏不统一。\n- 固定抽奖节点，开播前统一校对时钟，后台关注时间线并同步开奖与公布名单。\n\n直播 Pop-out／对比图视觉\n- 素材重点不突出、对比不明显。\n- 功效/疗程类产品只在需要长期使用才有变化时放对比图；即时体验产品如面膜，重点展示材质、精华液质地、流动性等。Content 精细化素材可直接作为 Pop-out。\n\n评论区与私信客服分工\n- 内服和护肤咨询量大，下单/抽奖问题回复不及时。\n- 私信少时后台客服主动去直播评论区引导，并私信有需要的观众。\n- 分工：Shopee 客服 Fyfy；Coforyou IG 私信 Alyssa；Coforyou 主账号 Angeline；Coco 账号 Wenqi。\n\n保健品合规与选品反馈\n- 严禁 over-promise，强调效果因人而异；孕妇、小孩、坐月子期间谨遵医嘱，购买前建议咨询医生。\n- 客服实时记录评论区呼声高的产品，作为后续选品和团购参考。\n- 直播间常态提醒观众加入拼单群，提高复购和凑单效率。",
    "summary": "会议重点\n- 直播前按配套清单逐项清点产品与道具，并按直播顺序摆放；团队需完整掌握产品成分、卖点、用法、适用人群及 FAQ。\n- 麦克风异常暂按 Instagram Bug 处理：主播和后台同步用 Pop-out/置顶评论提示观众退出重进，同时继续排查设备与网络。\n- 抽奖采用固定时间节点，开播前统一时钟，后台按时间线同步开奖和公布名单。\n- Pop-out 素材按产品类型制作：长期功效产品用对比图；即时体验产品放大材质、质地和流动性。\n- 客服根据 DM 数量动态分流：DM 少时主动进入直播评论并私信顾客。账号责任人为 Fyfy（Shopee）、Alyssa（Coforyou IG DM）、Angeline（Coforyou 主账号）、Wenqi（Coco 账号）。\n- 保健品内容禁止 over-promise，加入效果因人而异及特殊人群咨询医生提示；客服同步收集高需求产品，并持续引导加入拼单群。",
    "createdAt": "2026-08-11T08:13:00.000Z",
    "locked": true
  },
  {
    "id": "anniversary-review-2026-08-w2-alyssa",
    "department": "Team",
    "title": "周年庆复盘",
    "meetingDate": "2026-08-W2",
    "participantName": "Alyssa",
    "minutes": "1. 品牌熟悉度\n- 深入了解产品功效、卖点及消费者选择品牌的原因。宣传需从消费者角度思考为什么需要、为什么相信、为什么选择，而不只是品牌介绍。\n- 保健品避免“每个人都需要”等绝对表达，也不要过度聚焦单一 ingredient；从整体形象、使用场景、消费者需求和品牌印象宣传，避免医疗化或夸大。\n- Begin 避免直接提到减脂等功效联想；涉及 sodium 高等特点要谨慎，重点放在宣传与呈现方式。\n\n2. 抽奖流程\n- 前后台 communication 要有来有回、清楚即时。\n- 流程：Front 发出准确 Signal → Backend 收到后马上 PO → Jimun Pin → 通知 Front → 同步 CS Group。\n- 避免前后台各自进行，导致 signal 对不上、不同步或重复操作。\n\n3. 后台回复方式\n- DM 多时优先处理 DM，避免顾客等待。\n- DM 少时主动查看 Comment Section，发现需跟进顾客可直接 DM 小福宝处理。\n\n4. Reels\n- Reels 设置 Auto Reply，触发关键词后自动发送 link。\n- 上线前确认 Auto Reply link、Private Link、Coco Promo 是否一致、是否需要区分，统一后再设置。\n\n5. Sales\n- Jmoon 前期 Sales 太低会压缩后续铺垫时间。需提前规划 Sales Funnel、Content Preparation 和 Pre-heating，让消费者觉得“这是我需要的”，而不是“可以考虑”。\n\n6. 小红书晒单\n- 发布时必须完成 3 个 Hashtag，可列为固定发布 Checklist。\n\n7. Internal Workflow\n- Inbox 内容如有新 Edit，必须标记 Edited 并 tag accountable/responsible person，避免团队使用不同版本。\n\n8. 延期开卖\n- 延期前先确认目的、预期效果及对 Sales、Content、Community 的影响，再 align 团队并执行。\n\n9. 售后问题\n- 重要售后问题需在 Telegram 同步，并通知 Content Team 发生了什么、顾客反馈、处理阶段及需避免的 wording。\n- 准备统一 Notice Text Version，tag 相关团队并持续 update。\n- 流程：发现问题 → Telegram 通知 → Content Team → Notice Version → Tag Relevant Team → 持续 Update。\n\n10. Telegram Community\n- 拼单群制定明确 Group Rules：允许/禁止内容、拼单流程、Admin/Moderator 权限、互动与售后处理。\n- 每次开卖前发布 Pop-up Message，提前预热、通知时间和提醒顾客。\n- Review 现有 Telegram Groups：保留、整合、重新定位，并明确每组目的和负责人。\n- 明确 Admin/Moderator 的审核、回复、活跃和问题处理责任。\n- 群组不能只是买东西，要增加 Community 专属活动、互动、产品讨论、拼单、福利和小游戏，建立归属感。\n\n11. 小福管家形象\n- Telegram 统一使用小福管家视觉，连接 Community 与品牌角色。\n- 设计小福管家 GIF、表情包、日常回复、反应图和常见顾客情境用语。\n- 方向要贴切、接地气、有互动感，让小福管家成为有个性和辨识度的 Community 角色。\n\n总体重点\n- Brand：更了解品牌，更准确宣传，避免敏感/绝对 wording。\n- Operation：Signal 清楚，前后台同步，责任人明确。\n- Content：提前铺垫，明确 Sales 目的，统一表达。\n- CS：依 DM/Comment 数量灵活处理，重要售后及时同步。\n- Community：整理 Telegram、制定规则、明确分工并提高活跃。\n- 小福管家：统一视觉和角色表达。",
    "summary": "核心方向\n- 品牌内容必须从消费者需求与信任理由出发，不只复述品牌卖点；保健品和 Begin 等敏感品类避免绝对、医疗化、减脂或夸大表达。\n- 抽奖统一为：Front signal → Backend 即时发布 → Jimun pin → 回报 Front → CS Group 同步。\n- 客服按流量动态分工：DM 多优先 DM，DM 少主动巡查评论并私信需要协助的顾客。\n- Reels Auto Reply 上线前统一确认 Private Link、Coco Promo 和自动回复链接，避免不同版本。\n- Jmoon 等品牌要提前做 Sales Funnel、内容准备和预热；XHS 晒单固定检查 3 个 hashtag。\n- 所有内部修改标注 Edited 并 tag 负责人；延期前先定义目的和影响。\n\n售后与 Community\n- 重要售后按固定流程同步 Telegram、Content、Notice 文案和相关责任人，并持续更新进度。\n- 重新整理 Telegram 群组定位，制定拼单群规则和开卖前 Pop-up，明确 Admin/Moderator 的审核、回复、活跃和问题处理职责。\n- Community 需从单纯交易群转为有活动、讨论、福利和归属感的社群。\n- 统一小福管家视觉，发展 GIF、表情包、日常回复和情境反应图，建立亲切且有辨识度的角色。\n\nAction Items\n- Content/BD 建立敏感 wording 与品牌熟悉度检查。\n- Jimun 与前后台落实抽奖 signal SOP。\n- CS 建立 DM/Comment 分流、售后 Notice 与 Telegram 群规。\n- Community 团队整理现有群组、管理员职责和开卖预热机制。\n- 设计小福管家 Telegram 视觉、GIF 与表情包。",
    "createdAt": "2026-08-11T08:14:00.000Z",
    "locked": true
  }
];
